tasks:
  - name: Install tailwind
    init: |
      curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
      chmod +x tailwindcss-linux-x64
      mv tailwindcss-linux-x64 tailwindcss
    command: ./tailwindcss -i ./src/input.css -o ./dist/output.css --watch
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - ritwickdey.LiveServer
