tasks:
  - name: Install tailwind
    before: npm install -D tailwind
    init: echo "Your version of tailwind is `npx tailwindcss --help`"
    command: npx tailwindcss -i ./src/input.css -o ./dist/output.css --watch
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - ms-vscode.live-server
