tasks:
  - name: Serve files
    init: npm install
    command: npm start
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-browser

vscode:
  extensions:
    - ritwickdey.LiveServer
