baseURL = 'https://www.schildpad.app'
languageCode = 'en-us'
defaultContentLanguage = "en"

title = "Schildpad"
# copyright = "Copy, _right?_ :thinking_face:"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Joel Koch"
  # headline = "An awesome person"
  image = "img/schildpad_logo.svg"  # path relative to static directory

  links = [
    { fdroid = { href = "https://f-droid.org", text = "F-Droid" }},
    { googleplay = { href = "https://play.google.com", text = "Google Play" }},
    { github = "https://github.com/joelpaulkoch/schildpad" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
[[module.imports]]
  path = 'github.com/jpanther/lynx'
